# Generated by Django 4.2.1 on 2023-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField()),
                ('clossest_points', models.JSONField()),
            ],
            options={
                'db_table': 'points_table',
            },
        ),
    ]
