# Generated by Django 4.2.1 on 2023-05-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='clossest_points',
            new_name='closest_pair',
        ),
    ]
