# Generated by Django 4.2.1 on 2023-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_clossest_points_points_closest_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='points',
            new_name='points_data',
        ),
    ]
